// OTP generation function
// This function generates a 6-digit OTP (One Time Password) as a string  using Math.random() method
// The OTP is generated by multiplying a random number between 0 and 1 by 900000, adding 100000 to it, and converting it to a string
// The Math.floor() method is used to round down the generated number to the nearest integer
// The generated OTP is a string representation of a 6-digit number, which can be used for various purposes such as authentication, verification, etc.

// export const generateOTP = () =>
//   Math.floor(100000 + Math.random() * 900000).toString();

// export const generateOTP = () =>
//   Math.floor(100000 + Math.random() * 900000).toString();

export const generateOTP = () => {
  return Math.floor(100000 + Math.random() * 900000).toString();
};
